name: scr_project
description: "An HR Project"
publish_to: 'none' 

version: 1.0.0+1

platforms:
  web:
  windows:

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  #Cupertino Icons
  cupertino_icons:

  #File
  file_picker: 

  #Dialog
  month_picker_dialog: 

  #Fields
  flutter_masked_text2: 

  #Firebase
  firebase_core: 
  cloud_firestore: 
  firebase_auth: 

  #PDF
  syncfusion_flutter_pdf: 
  syncfusion_flutter_pdfviewer: 
  printing: 
  photo_view: 
  native_pdf_renderer:
  flutter_localizations: 
    sdk: flutter
    version: 
  pdf: 
  url_launcher:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true
  assets:
    - images/iasd-logo.png
    - images/logo_app.png
